github:
  slug:         eMerchantPay/woocommerce-ecp-plugin
  access_token: ENV['PRONTO_GITHUB_ACCESS_TOKEN']
  api_endpoint: ENV['PRONTO_GITHUB_API_ENDPOINT']
  web_endpoint: ENV['PRONTO_GITHUB_WEB_ENDPOINT']
verbose: false
